### ISSUE TITLE
Unable to access Tensorboard in JupyterLab

### ISSUE THREAD

**Issue by VaishnaviHire** [thoth-station/s2i-tensorflow-gpu-notebook#6]
When trying to run the notebook found at[ Get Started with Tensorboard](https://www.tensorflow.org/tensorboard/get_started#:~:text=TensorBoard%20is%20a%20tool%20for,dimensional%20space%2C%20and%20much%20more.), JupyterLab fails to display the Tensorboard pane in the notebook interface. Instead, it will return some non-specific error depending on the browser in use.

**To Reproduce**
1.  Deploy [s2i-tensorflow-gpu-notebook](https://github.com/thoth-station/s2i-tensorflow-gpu-notebook)
2. Run Tensorboard using instructions given in [Getting started](https://www.tensorflow.org/tensorboard/get_started#:~:text=TensorBoard%20is%20a%20tool%20for,dimensional%20space%2C%20and%20much%20more.) guide.
3. See error when running ```%tensorboard --logdir logs/fit``` cell.

**Expected behavior**
No error on ```%tensorboard --logdir logs/fit```

**Screenshots**

<img width="1315" alt="Screen Shot 2022-06-30 at 11 18 01 AM" src="https://user-images.githubusercontent.com/17230536/176714333-1a8da49f-efd9-4705-90b5-21bf0c97d3ec.png">

**Additional context**

**Comment by guimou** [comment]
This is a know issue for the jupyter-tensorboard extension: https://github.com/lspvic/jupyter_tensorboard/issues/43
What the command does is launching the tensorboard app. It has its own webserver that runs on port 6006. So it's launched and run in the container. But then what the visualizer is trying to access in the notebook is the address.of.the.server:6006. Which of course does not work as this port is not exposed.
Example:
* My notebook is running at: https://jupyterhub-redhat-ods-applications.apps.rhods-internal.61tk.p1.openshiftapps.com/user/gmoutier@redhat.com/lab
* And it tries to access the Tensorboard at https://jupyterhub-redhat-ods-applications.apps.rhods-internal.61tk.p1.openshiftapps.com:6006/
This address is just not reachable from the browser perspective... So the jupyter-tensorboard extension is doing its job, except that it's not aware that everything is running inside a container.

Two possible solutions:
* Completely rewrite the extension to make it compatible with the environment.
* Include the jupyter-server-proxy extension in the container image. With that extension you will be able to reach the tensorboard at address.of.the.server/user/username/proxy/6006 . Of course it won't display in the notebook because the extension won't know about this address. But you can still launch tensorboard (!tensorborad... or from Terminal view) and access it.

All of this will have to be reconsidered when switching to the KF Notebook controller as the mechanism is a little bit different. Maybe with this we will also be able to simply list some ports we want to expose by default for the images, regardless of if the process is running or not. But at least when launching it the service will be accessible.

**Comment by harshad16** [comment]
This already done with https://github.com/thoth-station/s2i-minimal-notebook/pull/560
Thanks to everyone for the help.
/remove-lifecycle stale
